import allure
from pages.order_page import OrderPage


@allure.suite('Проверяем оформление заказа')
class TestMakeOrder:

    @allure.description('Проверяем переадресацию на оформление зазаказ, нажав кнопку "Заказать" сверху справа страницы')
    @allure.title('Проверяем оформление заказа')
    def test_order_on_top_page(self, driver):
        check_top_page_order = OrderPage(driver=driver)
        check_top_page_order.click_to_accept_coockies()
        check_top_page_order.click_on_top_order_button()
        check_top_page_order.add_name()
        check_top_page_order.add_last_name()
        check_top_page_order.add_adress()
        check_top_page_order.add_metro_station_sokol()
        check_top_page_order.add_telephone_number()
        check_top_page_order.next_page()
        check_top_page_order.select_two_days_above_date()
        check_top_page_order.select_one_days_rent_period()
        check_top_page_order.select_black_color()
        check_top_page_order.add_comment_for_courier()
        check_top_page_order.next_page()
        check_top_page_order.click_on_button_yes()
        assert check_top_page_order.check_text_question_heading()

    @allure.description('Проверяем переадресацию на оформление зазаказа, нажав кнопку "Заказать" по середине страницы')
    @allure.title('Проверяем оформление заказа')
    def test_order_on_middle_page(self, driver):
        check_middle_page_order = OrderPage(driver=driver)
        check_middle_page_order.click_to_accept_coockies()
        check_middle_page_order.click_on_top_order_button()
        check_middle_page_order.add_name()
        check_middle_page_order.add_last_name()
        check_middle_page_order.add_adress()
        check_middle_page_order.add_metro_station_salarievo()
        check_middle_page_order.add_telephone_number()
        check_middle_page_order.next_page()
        check_middle_page_order.select_one_day_above_date()
        check_middle_page_order.select_seven_days_rent_period()
        check_middle_page_order.select_grey_color()
        check_middle_page_order.add_comment_for_courier()
        check_middle_page_order.next_page()
        check_middle_page_order.click_on_button_yes()
        assert check_middle_page_order.check_text_question_heading()


@allure.suite('Проверяем переадрессацию кликая на лого')
class TestClickOnLogos:

    @allure.description('Проверяем переадресацию на главную страницу по клику на логотип самоката находясь на странице оформленного заказа на самокат')
    @allure.title('Проверяем переадресацию на главную страницу по логотипу "Самокат"')
    def test_click_on_logo_samokat(self, driver):
        check_top_page_order = OrderPage(driver=driver)
        check_top_page_order.click_to_accept_coockies()
        check_top_page_order.click_on_top_order_button()
        check_top_page_order.add_name()
        check_top_page_order.add_last_name()
        check_top_page_order.add_adress()
        check_top_page_order.add_metro_station_sokol()
        check_top_page_order.add_telephone_number()
        check_top_page_order.next_page()
        check_top_page_order.select_two_days_above_date()
        check_top_page_order.select_one_days_rent_period()
        check_top_page_order.select_black_color()
        check_top_page_order.add_comment_for_courier()
        check_top_page_order.next_page()
        check_top_page_order.click_on_button_yes()
        check_top_page_order.go_to_order_status_page()
        check_top_page_order.go_to_main_page_by_click_on_logo()
        assert check_top_page_order.check_redirrect_to_main_page()

    @allure.description('Проверяем переадресацию на дзен по клику на логотип Яндекса находясь на странице оформленного заказа на самокат')
    @allure.title('Проверяем переадресацию на Дзен по логотипу "Яндекс"')
    def test_click_on_logo_yandex(self, driver):
        check_top_page_order = OrderPage(driver=driver)
        check_top_page_order.click_to_accept_coockies()
        check_top_page_order.click_on_top_order_button()
        check_top_page_order.add_name()
        check_top_page_order.add_last_name()
        check_top_page_order.add_adress()
        check_top_page_order.add_metro_station_sokol()
        check_top_page_order.add_telephone_number()
        check_top_page_order.next_page()
        check_top_page_order.select_two_days_above_date()
        check_top_page_order.select_one_days_rent_period()
        check_top_page_order.select_black_color()
        check_top_page_order.add_comment_for_courier()
        check_top_page_order.next_page()
        check_top_page_order.click_on_button_yes()
        check_top_page_order.go_to_order_status_page()
        check_top_page_order.go_to_dzen_page_by_click_on_logo()
        assert check_top_page_order.check_redirrect_to_dzen_page()
